x-api-vars: &api-vars
  DATABASE_URL: postgresql://redwood:redwood@db:5432/ExploreGame
  TEST_DATABASE_URL: postgresql://redwood:redwood@db:5432/ExploreGame_test
  SESSION_SECRET: super_secret_session_key_change_me_in_production_please
  MINIO_ACCESS_KEY: root
  MINIO_BUCKET: exploregame-assets

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: api_serve
    ports:
      - '8911:8911'
    depends_on:
      - db
    environment:
      <<: *api-vars

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: web_serve
    ports:
      - '8910:8910'
    depends_on:
      - api
    environment:
      - API_PROXY_TARGET=http://api:8911

  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: redwood
      POSTGRES_PASSWORD: redwood
      POSTGRES_DB: ExploreGame
    # ports:
    #   - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data

  console:
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile
      target: console
    tmpfs:
      - /tmp
    command: 'true'
    environment:
      - DATABASE_URL=postgresql://redwood:redwood@db:5432/ExploreGame
      - TEST_DATABASE_URL=postgresql://redwood:redwood@db:5432/ExploreGame_test
    depends_on:
      - db

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      # MINIO_NOTIFY_WEBHOOK_ENABLE: on
      # MINIO_NOTIFY_WEBHOOK_ENDPOINT: http://172.19.0.1:8911/webhook
    command: server --console-address ":9001" /data
    networks:
      - default